[2024-11-16T21:31:10.224+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-16T21:31:10.242+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Ciril_group.run-example manual__2024-11-16T21:31:08.983452+00:00 [queued]>
[2024-11-16T21:31:10.252+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Ciril_group.run-example manual__2024-11-16T21:31:08.983452+00:00 [queued]>
[2024-11-16T21:31:10.253+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 6
[2024-11-16T21:31:10.267+0000] {taskinstance.py:2888} INFO - Executing <Task(DockerOperator): run-example> on 2024-11-16 21:31:08.983452+00:00
[2024-11-16T21:31:10.277+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'Ciril_group', 'run-example', 'manual__2024-11-16T21:31:08.983452+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/ciril_group_dag.py', '--cfg-path', '/tmp/tmpq890uueb']
[2024-11-16T21:31:10.280+0000] {standard_task_runner.py:105} INFO - Job 4: Subtask run-example
[2024-11-16T21:31:10.280+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=199) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-16T21:31:10.281+0000] {standard_task_runner.py:72} INFO - Started process 201 to run task
[2024-11-16T21:31:10.325+0000] {task_command.py:467} INFO - Running <TaskInstance: Ciril_group.run-example manual__2024-11-16T21:31:08.983452+00:00 [running]> on host 02542b25ca0e
[2024-11-16T21:31:10.408+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Simo' AIRFLOW_CTX_DAG_ID='Ciril_group' AIRFLOW_CTX_TASK_ID='run-example' AIRFLOW_CTX_EXECUTION_DATE='2024-11-16T21:31:08.983452+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-16T21:31:08.983452+00:00'
[2024-11-16T21:31:10.409+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-16T21:31:10.512+0000] {docker.py:367} INFO - Starting docker container from image ***_ciril:latest
[2024-11-16T21:31:18.494+0000] {docker.py:438} INFO - 
[2024-11-16T21:31:20.648+0000] {docker.py:438} INFO - Fichier non trouv√© : [Errno 2] No such file or directory: '../data/people.csv'
[2024-11-16T21:31:21.428+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-16T21:31:21.429+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=Ciril_group, task_id=run-example, run_id=manual__2024-11-16T21:31:08.983452+00:00, execution_date=20241116T213108, start_date=20241116T213110, end_date=20241116T213121
[2024-11-16T21:31:21.477+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-11-16T21:31:21.501+0000] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-11-16T21:31:21.503+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
