[2024-11-16T22:18:51.636+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-16T22:18:51.653+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Ciril_group.load_to_db manual__2024-11-16T22:13:32.897013+00:00 [queued]>
[2024-11-16T22:18:51.662+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Ciril_group.load_to_db manual__2024-11-16T22:13:32.897013+00:00 [queued]>
[2024-11-16T22:18:51.662+0000] {taskinstance.py:2865} INFO - Starting attempt 2 of 6
[2024-11-16T22:18:51.674+0000] {taskinstance.py:2888} INFO - Executing <Task(DockerOperator): load_to_db> on 2024-11-16 22:13:32.897013+00:00
[2024-11-16T22:18:51.682+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'Ciril_group', 'load_to_db', 'manual__2024-11-16T22:13:32.897013+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/ciril_group_dag.py', '--cfg-path', '/tmp/tmpeeo_wqcq']
[2024-11-16T22:18:51.684+0000] {standard_task_runner.py:105} INFO - Job 12: Subtask load_to_db
[2024-11-16T22:18:51.687+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=254) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-16T22:18:51.688+0000] {standard_task_runner.py:72} INFO - Started process 255 to run task
[2024-11-16T22:18:51.719+0000] {task_command.py:467} INFO - Running <TaskInstance: Ciril_group.load_to_db manual__2024-11-16T22:13:32.897013+00:00 [running]> on host 473c7a96b1b4
[2024-11-16T22:18:51.781+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Simo' AIRFLOW_CTX_DAG_ID='Ciril_group' AIRFLOW_CTX_TASK_ID='load_to_db' AIRFLOW_CTX_EXECUTION_DATE='2024-11-16T22:13:32.897013+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-16T22:13:32.897013+00:00'
[2024-11-16T22:18:51.782+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-16T22:18:51.817+0000] {docker.py:367} INFO - Starting docker container from image ***_ciril:latest
[2024-11-16T22:18:56.466+0000] {local_task_job_runner.py:127} ERROR - Received SIGTERM. Terminating subprocesses
[2024-11-16T22:18:56.476+0000] {process_utils.py:132} INFO - Sending 15 to group 255. PIDs of all processes in the group: [255]
[2024-11-16T22:18:56.477+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 255
[2024-11-16T22:18:56.482+0000] {taskinstance.py:3092} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-11-16T22:18:56.484+0000] {docker.py:533} INFO - Stopping docker container
[2024-11-16T22:18:57.089+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 513, in execute
    return self._run_image()
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 372, in _run_image
    return self._run_image_with_mounts([*self.mounts, tmp_mount], add_tmp_variable=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 434, in _run_image_with_mounts
    for log_chunk in logstream:
                     ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/docker/types/daemon.py", line 29, in __next__
    return next(self._stream)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/docker/api/client.py", line 438, in <genexpr>
    gen = (data for (_, data) in gen)
                                 ^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/docker/utils/socket.py", line 101, in <genexpr>
    return ((STDOUT, frame) for frame in frames_iter_tty(socket))
                                         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/docker/utils/socket.py", line 133, in frames_iter_tty
    result = read(socket)
             ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/docker/utils/socket.py", line 40, in read
    poll.poll()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3094, in signal_handler
    raise AirflowTaskTerminated("Task received SIGTERM signal")
airflow.exceptions.AirflowTaskTerminated: Task received SIGTERM signal
[2024-11-16T22:18:57.342+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=Ciril_group, task_id=load_to_db, run_id=manual__2024-11-16T22:13:32.897013+00:00, execution_date=20241116T221332, start_date=20241116T221851, end_date=20241116T221857
[2024-11-16T22:18:57.366+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-16T22:18:57.399+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=255, status='terminated', exitcode=2, started='22:18:50') (255) terminated with exit code 2
[2024-11-16T22:18:57.401+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 143
[2024-11-16T22:18:57.433+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-16T22:18:57.462+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
