[2024-11-18T21:53:11.279+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-18T21:53:11.296+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Ciril_group_test.run-example manual__2024-11-18T21:53:10.420810+00:00 [queued]>
[2024-11-18T21:53:11.305+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Ciril_group_test.run-example manual__2024-11-18T21:53:10.420810+00:00 [queued]>
[2024-11-18T21:53:11.306+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 6
[2024-11-18T21:53:11.319+0000] {taskinstance.py:2888} INFO - Executing <Task(DockerOperator): run-example> on 2024-11-18 21:53:10.420810+00:00
[2024-11-18T21:53:11.326+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'Ciril_group_test', 'run-example', 'manual__2024-11-18T21:53:10.420810+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/ciril_group_dag.py', '--cfg-path', '/tmp/tmpnvs_s1tz']
[2024-11-18T21:53:11.328+0000] {standard_task_runner.py:105} INFO - Job 4: Subtask run-example
[2024-11-18T21:53:11.329+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=192) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-18T21:53:11.330+0000] {standard_task_runner.py:72} INFO - Started process 194 to run task
[2024-11-18T21:53:11.363+0000] {task_command.py:467} INFO - Running <TaskInstance: Ciril_group_test.run-example manual__2024-11-18T21:53:10.420810+00:00 [running]> on host 131e0c36cc7d
[2024-11-18T21:53:11.432+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Simo' AIRFLOW_CTX_DAG_ID='Ciril_group_test' AIRFLOW_CTX_TASK_ID='run-example' AIRFLOW_CTX_EXECUTION_DATE='2024-11-18T21:53:10.420810+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-18T21:53:10.420810+00:00'
[2024-11-18T21:53:11.433+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-18T21:53:11.494+0000] {docker.py:367} INFO - Starting docker container from image ***_ciril:latest
[2024-11-18T21:53:19.157+0000] {docker.py:438} INFO - 
[2024-11-18T21:53:21.039+0000] {docker.py:438} INFO - Fichier non trouv√© : [Errno 2] No such file or directory: '../data/people.csv'
[2024-11-18T21:53:21.677+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-18T21:53:21.677+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=Ciril_group_test, task_id=run-example, run_id=manual__2024-11-18T21:53:10.420810+00:00, execution_date=20241118T215310, start_date=20241118T215311, end_date=20241118T215321
[2024-11-18T21:53:21.727+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-11-18T21:53:21.760+0000] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-11-18T21:53:21.763+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
