[2024-11-16T21:25:14.081+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-16T21:25:14.103+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Ciril_group.run-example manual__2024-11-16T21:14:41.881025+00:00 [queued]>
[2024-11-16T21:25:14.115+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Ciril_group.run-example manual__2024-11-16T21:14:41.881025+00:00 [queued]>
[2024-11-16T21:25:14.116+0000] {taskinstance.py:2865} INFO - Starting attempt 3 of 6
[2024-11-16T21:25:14.133+0000] {taskinstance.py:2888} INFO - Executing <Task(DockerOperator): run-example> on 2024-11-16 21:14:41.881025+00:00
[2024-11-16T21:25:14.145+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'Ciril_group', 'run-example', 'manual__2024-11-16T21:14:41.881025+00:00', '--job-id', '78', '--raw', '--subdir', 'DAGS_FOLDER/ciril_group_dag.py', '--cfg-path', '/tmp/tmpxgxvv8ay']
[2024-11-16T21:25:14.147+0000] {standard_task_runner.py:105} INFO - Job 78: Subtask run-example
[2024-11-16T21:25:14.148+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=434) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-16T21:25:14.149+0000] {standard_task_runner.py:72} INFO - Started process 435 to run task
[2024-11-16T21:25:14.192+0000] {task_command.py:467} INFO - Running <TaskInstance: Ciril_group.run-example manual__2024-11-16T21:14:41.881025+00:00 [running]> on host 4bd64b07a953
[2024-11-16T21:25:14.266+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Simo' AIRFLOW_CTX_DAG_ID='Ciril_group' AIRFLOW_CTX_TASK_ID='run-example' AIRFLOW_CTX_EXECUTION_DATE='2024-11-16T21:14:41.881025+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-16T21:14:41.881025+00:00'
[2024-11-16T21:25:14.268+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-16T21:25:14.312+0000] {docker.py:367} INFO - Starting docker container from image ***_ciril:latest
[2024-11-16T21:25:21.210+0000] {docker.py:438} INFO - 
[2024-11-16T21:25:23.086+0000] {docker.py:438} INFO - Fichier non trouv√© : [Errno 2] No such file or directory: '../data/people.csv'
[2024-11-16T21:25:23.573+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-16T21:25:23.573+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=Ciril_group, task_id=run-example, run_id=manual__2024-11-16T21:14:41.881025+00:00, execution_date=20241116T211441, start_date=20241116T212514, end_date=20241116T212523
[2024-11-16T21:25:23.593+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-11-16T21:25:23.615+0000] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-11-16T21:25:23.617+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
